;; Skeleton des headers protege
(define-skeleton insert-protect-header
  "Inserts a define to protect the header file."
  ""
  '(setq str (file-name-sans-extension
          (file-name-nondirectory (buffer-file-name))))
  "#ifndef __"(upcase str)"_H__\n"
  "# define __"(upcase str)"_H__\n"
  "\n"
  "\n"
  "\n"
  "#endif /* !__"(upcase str)"_H__ */\n")

;; Skeleton des Makefiles
(define-skeleton create-makefile
  "Create a Makefile."
  ""
  "NAME        = \n"
  "\n"
  "SRCDIR        = src\n"
  "OBJDIR        = obj\n"
  "\n"
  "SRC        = \n"
  "\n"
  "LIB        = -Llib/ -lmy\n"
  "INC        = -I -Iinclude/\n"
  "\n"
  "OBJ        = $(SRC:.c=.o)\n"
  "CC        = /usr/bin/gcc\n"
  "CFLAGS        = -O2\n"
  "CDEBUG        = -W -Wall -ansi -pedantic -g -ggdb\n"
  "RM        = rm -f\n"
  "ECHO        = echo -e\n"
  "\n"
  "$(NAME)        : $(OBJ)\n"
  "          @$(CC) $(INC) $(CFLAGS) -o $(NAME) $(OBJDIR)/$(OBJ) $(LIB)\n"
  "          @$(ECHO) '\\033[0;32m> Compiled\\033[0m'\n"
  "\n"
  "clean        :\n"
  "          -@$(RM) $(OBJ)\n"
  "          -@$(RM) *~\n"
  "          -@$(RM) \#*\#\n"
  "          @$(ECHO) '\\033[0;35m> Directory cleaned\\033[0m'\n"
  "\n"
  "all        : $(NAME)\n"
  "\n"
  "fclean        : clean\n"
  "          -@$(RM) $(NAME)\n"
  "          @$(ECHO) '\\033[0;35m> Remove executable\\033[0m'\n"
  "\n"
  "re        : fclean all\n"
  "\n"
  ".PHONY        : all clean re\n"
  "\n"
  "debug        : $(OBJ)\n"
  "          @$(CC) $(INC) $(CDEBUG) -o $(NAME) $(OBJDIR)/$(OBJ) $(LIB)\n"
  "          @$(ECHO) '\\033[0;32m> Mode Debug: done\\033[0m'\n"
  "\n"
  ".c.o        : \n"
  "          $(CC) $(INC) $(CFLAGS) -o $(OBJDIR)/$@ -c $<\n")
